-- 테이블 생성 도구

--회원 데이터
CREATE TABLE MEMBER ( --테이블 이름
    USER_ID       NUMBER PRIMARY KEY, --아이디 PRIMARY KEY : 값의 증복, NULL값 입력을 방지
    USER_PASSWORD VARCHAR2(100), --비밀번호
    USER_NAME     VARCHAR2(30) NOT NULL, -- 이름
    USER_PHON     VARCHAR2(20) NOT NULL, --전화번호
    USER_ADDR1    VARCHAR2(20) NULL, --주소1
    USER_ADDR2    VARCHAR2(50) NULL, --주소2
    USER_ADDR3    VARCHAR2(50) NULL, --주소3
    REGI_DATE     DATE DEFAULT SYSDATE, --가입날짜
    VERIFY        NUMBER DEFAULT 0 --이메일 인증 여부
);

--상품 데이터
CREATE TABLE GOODS (
    GDS_NUM   NUMBER PRIMARY KEY, --상품번호
    GDS_NAME  VARCHAR2(50) NOT NULL, --상품이름
    CATE_CODE VARCHAR2(30) NOT NULL, --분류
    GDS_PRICE NUMBER NOT NULL, --가격
    GDS_STOCK NUMBER NULL, --수량
    GDS_DES   VARCHAR(500) NULL, --상품설명
    GDS_IMG   VARCHAR(200) NULL, --이미지
    GDS_DATE  DATE DEFAULT SYSDATE --등록날짜
);

--카테고리 데이터
CREATE TABLE GOODS_CATEGORY (
    CATE_NAME    VARCHAR2(20) NOT NULL,
    CATE_CODE    VARCHAR2(30) PRIMARY KEY,
    CATE_CODEREF VARCHAR2(30) NULL,
    FOREIGN KEY ( CATE_CODEREF )
        REFERENCES GOODS_CATEGORY ( CATE_CODE ) -- 카테고리 2차분류를 위한 외래키 주입
);

--카테고리 데이터에서 상품 데이터를 참조하기 위한 외래키 설정
ALTER TABLE GOODS
    ADD CONSTRAINT FK_GOODS_CATEGORY FOREIGN KEY ( CATE_CODE )
        REFERENCES GOODS_CATEGORY ( CATE_CODE );
        
--상품 번호 자동 입력을 위한 시퀀스 생성
CREATE SEQUENCE GOODS_SEQ;

--회원가입 테스트
INSERT INTO MEMBER(USER_ID, USER_PASSWORD, USER_NAME, USER_PHON)
VALUES (1, '비밀번호', '닉네임', '전화번호')

