-- 테이블 생성 도구

--회원 데이터
CREATE TABLE MEMBER ( --테이블 이름
    USERID       NUMBER PRIMARY KEY, --아이디 PRIMARY KEY : 값의 증복, NULL값 입력을 방지
    USERPASSWORD VARCHAR2(100), --비밀번호
    USERNAME     VARCHAR2(30) NOT NULL, -- 이름
    USERPHON     VARCHAR2(20) NOT NULL, --전화번호
    USERADDR1    VARCHAR2(20) NULL, --주소1
    USERADDR2    VARCHAR2(50) NULL, --주소2
    USERADDR3    VARCHAR2(50) NULL, --주소3
    REGIDATE     DATE DEFAULT SYSDATE, --가입날짜
    VERIFY       NUMBER DEFAULT 0 --이메일 인증 여부
);

--상품 데이터
CREATE TABLE GOODS (
    GDSNUM   NUMBER PRIMARY KEY, --상품번호
    GDSNAME  VARCHAR2(50) NOT NULL, --상품이름
    CATECODE VARCHAR2(30) NOT NULL, --분류
    GDSPRICE NUMBER NOT NULL, --가격
    GDSSTOCK NUMBER NULL, --수량
    GDSDES   VARCHAR(500) NULL, --상품설명
    GDSIMG   VARCHAR(200) NULL, --이미지
    GDSDATE  DATE DEFAULT SYSDATE --등록날짜
);

--카테고리 데이터
CREATE TABLE GOODS_CATEGORY (
    CATENAME    VARCHAR2(20) NOT NULL,
    CATECODE    VARCHAR2(30) PRIMARY KEY,
    CATECODEREF VARCHAR2(30) NULL,
    FOREIGN KEY ( CATECODEREF )
        REFERENCES GOODS_CATEGORY ( CATECODE ) -- 카테고리 2차분류를 위한 외래키 주입
);

--카테고리 데이터에서 상품 데이터를 참조하기 위한 외래키 설정
ALTER TABLE GOODS
    ADD CONSTRAINT FK_GOODS_CATEGORY FOREIGN KEY ( CATECODE )
        REFERENCES GOODS_CATEGORY ( CATECODE );
        
--상품 번호 자동 입력을 위한 시퀀스 생성
CREATE SEQUENCE GOODS_SEQ;